USE BRASIL_COVID
SELECT * FROM POP_MUNIC

CREATE TABLE DIM_ESTADO (
[COD_UF] INT,
[UF] VARCHAR (2),
[NOME_UF] VARCHAR (250),
[POP_ESTADO] INT )

CREATE TABLE DIM_MUNICIPIO (
[COD_UF] INT,
[COD_MUNIC] INT,
[NOME_MUNIC] VARCHAR (250),
[POP_MUNIC] INT )

CREATE TABLE DIM_PIB_MUNIC (
[COD_MUNIC] INT,
[ANO] INT,
[PIB] NUMERIC
)
DROP TABLE STAGE_COVID
CREATE TABLE STAGE_COVID (
[ID] VARCHAR (250),
[DT_NOTIF] DATE,
[CONDICOES] VARCHAR (250),
[SEXO] VARCHAR (250),
[COD_MUNIC] INT,
[IDADE] INT,
[EVOLUCAO] VARCHAR (250),
[ESTADO_TESTE] VARCHAR (250),
[RESULTADO_TESTE] VARCHAR (250),
[PIB] INT )


